# This file was generated by GoReleaser. DO NOT EDIT.
cask "multirun" do
  name "multirun"
  desc "Run multiple commands concurrently"
  homepage "https://github.com/ericfialkowski/multirun"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "multirun"

  on_macos do
    on_intel do
      url "https://github.com/ericfialkowski/multirun/releases/download/v#{version}/multirun_#{version}_darwin_amd64.tar.gz"
      sha256 "8fa592e0178a6b5ff3ca8f7e72cc48dc611904fb38f6f0cf1fbf96836d340c93"
    end
    on_arm do
      url "https://github.com/ericfialkowski/multirun/releases/download/v#{version}/multirun_#{version}_darwin_arm64.tar.gz"
      sha256 "7985ce53af6361e5ffc93ec796165cf4f1eef00a48f3ac5d1bdc880b385a09be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ericfialkowski/multirun/releases/download/v#{version}/multirun_#{version}_linux_amd64.tar.gz"
      sha256 "984fe5f08d4d91ebfe0812536623b01fc01db14bf9e908284a44ba17d2a93774"
    end
    on_arm do
      url "https://github.com/ericfialkowski/multirun/releases/download/v#{version}/multirun_#{version}_linux_arm64.tar.gz"
      sha256 "fb1affff7257ef85dc1c5415332696beea6f0f959e421ee9b259ff0c62426ff7"
    end
  end

  # No zap stanza required
end
